# Energy Star Scenario Configuration

dataset_name: AIEnergyScore/text_generation
text_column_name: text
num_samples: 1000
truncation: true
reasoning: false
input_shapes:
  batch_size: 1
generate_kwargs:
  max_new_tokens: 100
  min_new_tokens: 50
