services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  curl_command:
    image: curlimages/curl:latest
    command: >
      curl -X POST http://ollama:11434/api/pull -d '{
        "model": "llama3.2"
      }'

  ai_energy_benchmarks:
    image: ghcr.io/neuralwatt/ai_energy_benchmarks:latest
    build:
      context: .
    volumes:
      - ./benchmark_output:/app/benchmark_output
    depends_on:
      curl_command:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 

volumes:
  ollama: