services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  curl_command:
    image: curlimages/curl:latest
    depends_on:
      ollama:
        condition: service_started
    command: >
      curl -X POST http://ollama:11434/api/pull -d '{
        "model": "llama3.2"
      }'

  ai_energy_benchmarks:
    image: ghcr.io/neuralwatt/ai_energy_benchmarks:latest
    build:
      context: .
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia

volumes:
  ollama:
