name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - ppe

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.NEURALWATT_GHCR_RW }}

      - name: Extract version
        id: extract_version
        run: echo "::set-output name=version::$(cat VERSION.txt)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}:latest' || '' }}
            ${{ github.ref == 'refs/heads/ppe' && 'ghcr.io/${{ github.repository }}:latest_ppe' || '' }}
